language: ruby
script: rake coverage
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - Gemfile

# Install & start SSDB
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsnappy-dev
  - git clone --depth 1 -b scripting git://github.com/dim/ssdb.git
  - cd ssdb
  - make
  - cd ..

# Start SSDB
before_script:
  - cd ssdb
  - ./ssdb-server ssdb.conf -d

# Gracefully stop SSDB
after_script:
  - killall -w ssdb-server
