language: ruby
script: rake coverage
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - Gemfile

# Install & start SSDB
before_install:
  - git clone --depth 1 git://github.com/ideawu/ssdb.git
  - cd ssdb
  - make
  - cd ..

# Start SSDB
before_script:
  - cd ssdb
  - ./ssdb-server ssdb.conf

# Gracefully stop SSDB
after_script:
  - killall -w ssdb-server
